'use client'

import { useState } from 'react'
import { CheckCircle, XCircle, AlertCircle, Wrench, Pencil, FileText, Mail } from 'lucide-react'
import { updateTransactionWithOptimisticLock, createAdjustmentTransaction, editTransactionFieldsAction, applyTransactionAdjustmentAction } from '../actions'
import { cancelTransactionAction, revertTransactionAction } from '../contratos/actions'

interface Props {
  transactionId: string;
  currentStatus: string;
  xmin: string;
  type: string;
  isAutoGenerated?: boolean;
  recurrenceGroupId?: string | null;
  notes?: string | null;
  dueDate?: string | null;
  categories?: { id: string; name: string; type: string }[];
}

export default function TransactionAction({
  transactionId, currentStatus, xmin, type, isAutoGenerated,
  recurrenceGroupId, notes, dueDate
}: Props) {
  const [isLoading, setIsLoading] = useState(false)
  const [errorMsg, setErrorMsg] = useState('')
  const [showAdjustModal, setShowAdjustModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [adjAmount, setAdjAmount] = useState('')
  const [adjNotes, setAdjNotes] = useState('')
  const [editNotes, setEditNotes] = useState(notes ?? '')
  const [editScope, setEditScope] = useState<'this' | 'all'>('this')

  const [showLiquidarModal, setShowLiquidarModal] = useState(false)
  const [liquidarDate, setLiquidarDate] = useState('')

  const [emailSending, setEmailSending] = useState(false)
  const [emailSent,    setEmailSent]    = useState(false)
  const [emailError,   setEmailError]   = useState('')

  const handleSendEmail = async () => {
    setEmailSending(true)
    setEmailError('')
    try {
      const res = await fetch('/api/email/recibo', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ transactionId }),
      })
      const data = await res.json()
      if (!res.ok) setEmailError(data.error ?? 'Erro ao enviar.')
      else setEmailSent(true)
    } catch {
      setEmailError('Erro de rede ao enviar.')
    } finally {
      setEmailSending(false)
    }
  }

  const [showDiscountModal, setShowDiscountModal] = useState(false)
  const [discountAmount, setDiscountAmount] = useState('')
  const [additionAmount, setAdditionAmount] = useState('')
  const [adjustmentNotes, setAdjustmentNotes] = useState('')

  const handleLiquidar = async () => {
    setIsLoading(true)
    setErrorMsg('')
    try {
      await updateTransactionWithOptimisticLock(transactionId, 'paid', xmin, liquidarDate || undefined)
      setShowLiquidarModal(false)
    } catch (err) {
      setErrorMsg((err as Error).message || 'Erro ao liquidar')
    } finally {
      setIsLoading(false)
    }
  }

  const handleCancelar = async () => {
    const acao = isAutoGenerated ? 'anular esta fatura auto-gerada' : 'cancelar esta transação'
    if (!window.confirm(`Confirmar: ${acao}? Esta ação é irreversível.`)) return

    setIsLoading(true)
    setErrorMsg('')
    const err = await cancelTransactionAction(transactionId)
    setIsLoading(false)
    if (err) setErrorMsg(err)
  }

  const handleEstornar = async () => {
    if (!window.confirm('Reverter esta liquidação para Pendente? O valor pago será desconsiderado.')) return
    setIsLoading(true)
    setErrorMsg('')
    const err = await revertTransactionAction(transactionId)
    setIsLoading(false)
    if (err) setErrorMsg(err)
  }

  const handleAdjustment = async () => {
    const val = parseFloat(adjAmount)
    if (!val || isNaN(val)) { setErrorMsg('Informe um valor válido'); return }
    setIsLoading(true)
    setErrorMsg('')
    try {
      await createAdjustmentTransaction(transactionId, val, adjNotes)
      setShowAdjustModal(false)
      setAdjAmount('')
      setAdjNotes('')
    } catch (err) {
      setErrorMsg((err as Error).message || 'Erro ao criar ajuste')
    } finally {
      setIsLoading(false)
    }
  }

  const handleEditFields = async () => {
    setIsLoading(true)
    setErrorMsg('')
    try {
      await editTransactionFieldsAction(
        transactionId, xmin, editNotes || null, null,
        editScope, recurrenceGroupId ?? null
      )
      setShowEditModal(false)
    } catch (err) {
      setErrorMsg((err as Error).message || 'Erro ao editar')
    } finally {
      setIsLoading(false)
    }
  }

  const handleApplyAdjustment = async () => {
    const disc = parseFloat(discountAmount) || 0
    const add = parseFloat(additionAmount) || 0
    if (disc === 0 && add === 0) {
      setErrorMsg('Informe um valor de desconto ou acréscimo válido.')
      return
    }
    if (!adjustmentNotes.trim()) {
      setErrorMsg('Informe o motivo do ajuste.')
      return
    }
    
    setIsLoading(true)
    setErrorMsg('')
    try {
      await applyTransactionAdjustmentAction(transactionId, xmin, disc, add, adjustmentNotes)
      setShowDiscountModal(false)
    } catch (err) {
      setErrorMsg((err as Error).message || 'Erro ao aplicar ajuste')
    } finally {
      setIsLoading(false)
    }
  }

  const modalBg: React.CSSProperties = {
    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
    background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center',
    justifyContent: 'center', zIndex: 9999
  }
  const modalBox: React.CSSProperties = {
    background: '#1a1a2e', borderRadius: '16px', padding: '28px',
    border: '1px solid rgba(255,255,255,0.1)', maxWidth: '420px', width: '100%'
  }
  const inputStyle: React.CSSProperties = {
    width: '100%', padding: '10px 14px', borderRadius: '10px',
    background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)',
    color: 'white', fontSize: '14px', outline: 'none', boxSizing: 'border-box'
  }

  // ── PAID ──
  if (currentStatus === 'paid') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '6px' }}>
        <span style={{ color: 'var(--success-color)', fontSize: '13px', fontWeight: 600, padding: '4px 10px', background: 'var(--success-bg)', borderRadius: '12px' }}>
          Liq. Efetivada
        </span>
        <div style={{ display: 'flex', gap: '6px' }}>
          {/* Auto-gerada paid → Criar Ajuste (Inv. #8) */}
          {isAutoGenerated && (
            <button
              onClick={() => setShowAdjustModal(true)}
              style={{ background: 'rgba(99,102,241,0.1)', color: 'var(--accent-color)', border: '1px solid rgba(99,102,241,0.2)', padding: '3px 8px', borderRadius: '6px', cursor: 'pointer', fontSize: '11px', display: 'flex', alignItems: 'center', gap: '3px' }}
            >
              <Wrench size={10} /> Ajuste
            </button>
          )}
          {/* Recibo + Enviar por e-mail — apenas receitas liquidadas */}
          {type === 'income' && (
            <>
              <a
                href={`/dashboard/recibo/${transactionId}`}
                target="_blank"
                rel="noopener noreferrer"
                style={{ background: 'rgba(255,255,255,0.05)', color: 'var(--text-secondary)', border: '1px solid rgba(255,255,255,0.1)', padding: '3px 8px', borderRadius: '6px', cursor: 'pointer', fontSize: '11px', display: 'flex', alignItems: 'center', gap: '3px', textDecoration: 'none' }}
              >
                <FileText size={10} /> Recibo
              </a>
              <button
                onClick={handleSendEmail}
                disabled={emailSending || emailSent}
                title={emailSent ? 'Recibo enviado' : 'Enviar recibo por e-mail ao inquilino'}
                style={{
                  background: emailSent ? 'rgba(52,211,153,0.12)' : 'rgba(129,140,248,0.1)',
                  color: emailSent ? '#34d399' : 'var(--accent-color)',
                  border: `1px solid ${emailSent ? 'rgba(52,211,153,0.3)' : 'rgba(129,140,248,0.2)'}`,
                  padding: '3px 8px', borderRadius: '6px', cursor: emailSent ? 'default' : 'pointer',
                  fontSize: '11px', display: 'flex', alignItems: 'center', gap: '3px',
                  opacity: emailSending ? 0.6 : 1,
                }}
              >
                <Mail size={10} />
                {emailSent ? 'Enviado' : emailSending ? '...' : 'E-mail'}
              </button>
            </>
          )}
          {emailError && (
            <span style={{ fontSize: '10px', color: 'var(--danger-color)', background: 'var(--danger-bg)', padding: '2px 6px', borderRadius: '4px', maxWidth: '180px', whiteSpace: 'normal', lineHeight: 1.3 }}>
              {emailError}
            </span>
          )}
          {/* Estornar → reverte paid para pending */}
          <button
            onClick={handleEstornar}
            disabled={isLoading}
            style={{ background: 'transparent', color: 'var(--text-muted)', border: 'none', padding: '2px 6px', borderRadius: '6px', cursor: 'pointer', fontSize: '11px', opacity: isLoading ? 0.5 : 1 }}
          >
            Estornar
          </button>
        </div>

        {/* Modal de Ajuste */}
        {showAdjustModal && (
          <div style={modalBg} onClick={() => setShowAdjustModal(false)}>
            <div style={modalBox} onClick={e => e.stopPropagation()}>
              <h3 style={{ color: 'white', margin: '0 0 16px', fontSize: '16px' }}>
                <Wrench size={16} style={{ marginRight: '8px', display: 'inline' }} />
                Transação de Ajuste
              </h3>
              <p style={{ color: 'var(--text-secondary)', fontSize: '13px', marginBottom: '16px', lineHeight: 1.5 }}>
                Fatura auto-gerada e liquidada é imutável (Inv. #8). Crie uma transação de ajuste vinculada com <code style={{ fontSize: '11px' }}>parent_transaction_id</code>.
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                <div>
                  <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Valor do Ajuste (+ ou -)</label>
                  <input type="number" step="0.01" value={adjAmount} onChange={e => setAdjAmount(e.target.value)} style={inputStyle} placeholder="Ex: -150.00 ou 200.00" />
                </div>
                <div>
                  <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Motivo</label>
                  <input type="text" value={adjNotes} onChange={e => setAdjNotes(e.target.value)} style={inputStyle} placeholder="Diferença de multa, desconto..." />
                </div>
                <button onClick={handleAdjustment} disabled={isLoading} style={{ padding: '12px', borderRadius: '10px', background: 'var(--accent-color)', color: 'white', border: 'none', cursor: 'pointer', fontWeight: 600, opacity: isLoading ? 0.5 : 1 }}>
                  Criar Ajuste
                </button>
              </div>
            </div>
          </div>
        )}
        {errorMsg && <ErrorBadge msg={errorMsg} />}
      </div>
    )
  }

  // ── CANCELLED ──
  if (currentStatus === 'cancelled') {
    return <span style={{ color: 'var(--text-muted)', fontSize: '13px', fontWeight: 600, padding: '4px 10px', background: 'rgba(255,255,255,0.05)', borderRadius: '12px' }}>Baixa Nula</span>
  }

  // ── PENDING / LATE ──
  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '8px' }}>
      <div style={{ display: 'flex', gap: '6px' }}>
        {/* Editar notas/categoria */}
        <button
          onClick={() => { setEditNotes(notes ?? ''); setShowEditModal(true) }}
          style={{ background: 'rgba(255,255,255,0.05)', color: 'var(--text-secondary)', border: '1px solid rgba(255,255,255,0.1)', padding: '6px 10px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '3px' }}
          title="Editar notas"
        >
          <Pencil size={13} />
        </button>

        {/* Aplicar Desconto/Acréscimo */}
        <button
          onClick={() => setShowDiscountModal(true)}
          style={{ background: 'rgba(255,180,0,0.1)', color: 'var(--warning-color)', border: '1px solid rgba(255,180,0,0.2)', padding: '6px 10px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '3px' }}
          title="Aplicar Desconto ou Acréscimo"
        >
          <Wrench size={13} />
        </button>

        <button
          onClick={() => { setLiquidarDate(dueDate?.split('T')[0] ?? ''); setShowLiquidarModal(true) }}
          disabled={isLoading}
          style={{ background: 'var(--success-bg)', color: 'var(--success-color)', border: '1px solid rgba(0,255,100,0.2)', padding: '6px 12px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', opacity: isLoading ? 0.5 : 1, fontWeight: 'bold' }}
        >
          <CheckCircle size={14} />
          Liquidar
        </button>
        
        <button 
          onClick={handleCancelar}
          disabled={isLoading}
          style={{ background: 'var(--danger-bg)', color: 'var(--danger-color)', border: '1px solid rgba(255,50,50,0.2)', padding: '6px 12px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', opacity: isLoading ? 0.5 : 1, fontWeight: 'bold' }}
        >
          <XCircle size={14} />
          Cancelar
        </button>
      </div>

      {/* Modal de Liquidação com data */}
      {showLiquidarModal && (
        <div style={modalBg} onClick={() => setShowLiquidarModal(false)}>
          <div style={modalBox} onClick={e => e.stopPropagation()}>
            <h3 style={{ color: 'white', margin: '0 0 12px', fontSize: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <CheckCircle size={16} color="var(--success-color)" />
              Confirmar Liquidação
            </h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '13px', marginBottom: '16px' }}>
              Deixe em branco para usar a data de hoje.
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <div>
                <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Data do Recebimento</label>
                <input
                  type="date"
                  value={liquidarDate}
                  onChange={e => setLiquidarDate(e.target.value)}
                  style={{ ...inputStyle, colorScheme: 'dark' }}
                />
              </div>
              <div style={{ display: 'flex', gap: '8px' }}>
                <button onClick={() => setShowLiquidarModal(false)} style={{ flex: 1, padding: '10px', borderRadius: '10px', background: 'transparent', border: '1px solid var(--border-color)', color: 'var(--text-secondary)', cursor: 'pointer' }}>
                  Cancelar
                </button>
                <button onClick={handleLiquidar} disabled={isLoading} style={{ flex: 2, padding: '10px', borderRadius: '10px', background: 'var(--success-bg)', color: 'var(--success-color)', border: '1px solid rgba(0,255,100,0.2)', fontWeight: 700, cursor: 'pointer', opacity: isLoading ? 0.5 : 1 }}>
                  {isLoading ? 'Liquidando...' : 'Confirmar'}
                </button>
              </div>
              {errorMsg && <ErrorBadge msg={errorMsg} />}
            </div>
          </div>
        </div>
      )}

      {/* Modal de Edição — "Só esta" / "Todas" para séries */}
      {showEditModal && (
        <div style={modalBg} onClick={() => setShowEditModal(false)}>
          <div style={modalBox} onClick={e => e.stopPropagation()}>
            <h3 style={{ color: 'white', margin: '0 0 16px', fontSize: '16px' }}>
              <Pencil size={16} style={{ marginRight: '8px', display: 'inline' }} />
              Editar Transação
            </h3>
            {isAutoGenerated && (
              <p style={{ color: 'var(--warning-color)', fontSize: '12px', background: 'var(--warning-bg)', padding: '8px 12px', borderRadius: '8px', marginBottom: '12px' }}>
                Fatura auto-gerada: apenas notas e categoria podem ser editadas.
              </p>
            )}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <div>
                <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Observações</label>
                <textarea value={editNotes} onChange={e => setEditNotes(e.target.value)} style={{ ...inputStyle, minHeight: '60px', resize: 'vertical' }} placeholder="Notas sobre a transação..." />
              </div>

              {/* Escopo para séries recorrentes */}
              {recurrenceGroupId && (
                <div style={{ background: 'rgba(99,102,241,0.05)', border: '1px solid rgba(99,102,241,0.2)', borderRadius: '10px', padding: '12px' }}>
                  <p style={{ fontSize: '12px', color: 'var(--accent-color)', fontWeight: 600, marginBottom: '8px' }}>Escopo da edição (série recorrente)</p>
                  <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px', color: 'var(--text-secondary)', cursor: 'pointer', marginBottom: '6px' }}>
                    <input type="radio" name="scope" checked={editScope === 'this'} onChange={() => setEditScope('this')} /> Só esta ocorrência
                  </label>
                  <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px', color: 'var(--text-secondary)', cursor: 'pointer' }}>
                    <input type="radio" name="scope" checked={editScope === 'all'} onChange={() => setEditScope('all')} /> Todas as ocorrências do grupo
                  </label>
                </div>
              )}

              <button onClick={handleEditFields} disabled={isLoading} style={{ padding: '12px', borderRadius: '10px', background: 'var(--accent-color)', color: 'white', border: 'none', cursor: 'pointer', fontWeight: 600, opacity: isLoading ? 0.5 : 1 }}>
                Salvar Alterações
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Modal de Desconto / Acréscimo */}
      {showDiscountModal && (
        <div style={modalBg} onClick={() => setShowDiscountModal(false)}>
          <div style={modalBox} onClick={e => e.stopPropagation()}>
            <h3 style={{ color: 'white', margin: '0 0 16px', fontSize: '16px' }}>
              <Wrench size={16} style={{ marginRight: '8px', display: 'inline' }} />
              Aplicar Desconto / Acréscimo
            </h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '12px', marginBottom: '16px', lineHeight: 1.5 }}>
              Altere o valor desta fatura adicionando descontos ou multas. O valor original será mantido no histórico para fins de auditoria.
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              <div>
                <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Desconto (R$)</label>
                <input type="number" step="0.01" value={discountAmount} onChange={e => setDiscountAmount(e.target.value)} style={inputStyle} placeholder="Ex: 500.00" />
              </div>
              <div>
                <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Acréscimo / Multa Extra (R$)</label>
                <input type="number" step="0.01" value={additionAmount} onChange={e => setAdditionAmount(e.target.value)} style={inputStyle} placeholder="Ex: 50.00" />
              </div>
              <div>
                <label style={{ fontSize: '12px', color: 'var(--text-muted)', display: 'block', marginBottom: '4px' }}>Motivo (Obrigatório)</label>
                <input type="text" value={adjustmentNotes} onChange={e => setAdjustmentNotes(e.target.value)} style={inputStyle} placeholder="Ex: Pro-rata de 15 dias" />
              </div>
              <button onClick={handleApplyAdjustment} disabled={isLoading} style={{ padding: '12px', borderRadius: '10px', background: 'var(--warning-bg)', color: 'var(--warning-color)', border: '1px solid var(--warning-color)', cursor: 'pointer', fontWeight: 600, opacity: isLoading ? 0.5 : 1 }}>
                Confirmar Ajuste
              </button>
            </div>
          </div>
        </div>
      )}
      
      {errorMsg && <ErrorBadge msg={errorMsg} />}
    </div>
  )
}

function ErrorBadge({ msg }: { msg: string }) {
  return (
    <span style={{ color: 'var(--warning-color)', fontSize: '12px', maxWidth: '260px', textAlign: 'right', background: 'var(--warning-bg)', padding: '6px 10px', borderRadius: '6px', border: '1px solid var(--warning-color)', marginTop: '4px', display: 'flex', alignItems: 'center', gap: '6px' }}>
      <AlertCircle size={12} />
      {msg}
    </span>
  )
}
